---
title: "Modeling Crop Yield for Wheat on Meteo and Soild Data"
author: "Group Name"
date: "01/09/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## intro 
## Introduction

Text\


## Step 0: Getting R ready for the task 

Text\

```{r libraries, echo=TRUE, warning=FALSE, message=FALSE}

library (here)
library (tidyverse) 
library (dbplyr)
library(stringr)
library (ggplot2)

```


## Step 1: Getting R Data

Text\

```{r read, echo=TRUE, warning=FALSE, message=FALSE}

# Reading csv file and skipping the first 4 rows then assigning to tibble (yield_area_raw)
# (Data from: https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/7121.02015-16?OpenDocument)

yield_area_raw <- read_csv(here::here("project/src/data", "7121DO004_201516.csv"), skip = 4)


```


## Step 2: Tyding Data

Text \

```{r tidy data, echo=TRUE, warning=FALSE, message=FALSE}

# Select and filter Wheat and Area (ha)

yield_area_1_tidy <- yield_area_raw %>% 
  select ('Region label', 'Commodity description', 'Estimate')
  
colnames(yield_area_1_tidy) <- c("region", "description", "yield")

yield_area_1_tidy <- yield_area_1_tidy %>%  
  filter(str_detect(description, "Wheat")) %>% 
  filter(str_detect(description, "Yield")) %>% 
  select ('region', 'yield')

# Select and filter Wheat and Yiel (t/ha) 

yield_area_2_tidy <- yield_area_raw %>% 
  select ('Region label', 'Commodity description', 'Estimate')

colnames(yield_area_2_tidy) <- c("region", "description", "area")

yield_area_2_tidy <- yield_area_2_tidy %>%  
  filter(str_detect(description, "Wheat")) %>% 
  filter(str_detect(description, "Area")) %>% 
  select ('region', 'area')

# Join   

region_yield_area_tidy <- left_join(yield_area_1_tidy, yield_area_2_tidy)

```


Merged with a `left_join`. \


```{r merge data, echo=TRUE, warning=FALSE, message=FALSE}

# Merge Data 

# tibbname <- left_join(tibb1, tibb2)

```

Text \


## Step 3: Visualisation 

Text \


```{r visualisation, echo=TRUE, warning=FALSE, message=FALSE}

# Visualising Data

# ggplot(mod_data) +
#   geom_point(mapping = aes(x = confirmed, y = PMSP_16)) +
#   geom_smooth(method = lm, aes(x = confirmed, y = PMSP_16), size = 0.5, se = FALSE) +
#   ylab("Title y-axis") +
#   xlab("Title x-axis") +  ggtitle("Titel", subtitle = "Dates")
    
```            



### Step 4: Modelling

Text \
   
```{r linear reg, echo=TRUE, warning=FALSE, message=FALSE}    

# Regression

# mod <- lm(independentvar ~ responsevar, mod_data)

# summary(mod)


```


Text \


## Step 5: Conclusion/Communication 

Text. 


